In [1]:
import pandas as pd

In [2]:
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_excel('DS - Assignment Part 1 data set.xlsx')
df.head()

Transaction date  House Age  Distance from nearest Metro station (km)  \
0       2012.916667       32.0                                  84.87882   
1       2012.916667       19.5                                 306.59470   
2       2013.583333       13.3                                 561.98450   
3       2013.500000       13.3                                 561.98450   
4       2012.833333        5.0                                 390.56840   

   Number of convenience stores  latitude  longitude  Number of bedrooms  \
0                            10  24.98298  121.54024                   1   
1                             9  24.98034  121.53951                   2   
2                             5  24.98746  121.54391                   3   
3                             5  24.98746  121.54391                   2   
4                             5  24.97937  121.54245                   1   

   House size (sqft)  House price of unit area  
0                575                      37.9  
1               1240                      42.2  
2               1060                      47.3  
3                875                      54.8  
4                491                      43.1

In [10]:
df.rename(columns = {'House price of unit area':'Price'}, inplace = True)
df

Transaction date  House Age  Distance from nearest Metro station (km)  \
0         2012.916667       32.0                                  84.87882   
1         2012.916667       19.5                                 306.59470   
2         2013.583333       13.3                                 561.98450   
3         2013.500000       13.3                                 561.98450   
4         2012.833333        5.0                                 390.56840   
..                ...        ...                                       ...   
409       2013.000000       13.7                                4082.01500   
410       2012.666667        5.6                                  90.45606   
411       2013.250000       18.8                                 390.96960   
412       2013.000000        8.1                                 104.81010   
413       2013.500000        6.5                                  90.45606   

     Number of convenience stores  latitude  longitude  Number of bedrooms  \
0                              10  24.98298  121.54024                   1   
1                               9  24.98034  121.53951                   2   
2                               5  24.98746  121.54391                   3   
3                               5  24.98746  121.54391                   2   
4                               5  24.97937  121.54245                   1   
..                            ...       ...        ...                 ...   
409                             0  24.94155  121.50381                   3   
410                             9  24.97433  121.54310                   2   
411                             7  24.97923  121.53986                   1   
412                             5  24.96674  121.54067                   1   
413                             9  24.97433  121.54310                   2   

     House size (sqft)  Price  
0                  575   37.9  
1                 1240   42.2  
2                 1060   47.3  
3                  875   54.8  
4                  491   43.1  
..                 ...    ...  
409                803   15.4  
410               1278   50.0  
411                503   40.6  
412                597   52.5  
413               1097   63.9  

[414 rows x 9 columns]

In [11]:
X =df.drop(['Transaction date','Price'],axis='columns')
X

House Age  Distance from nearest Metro station (km)  \
0         32.0                                  84.87882   
1         19.5                                 306.59470   
2         13.3                                 561.98450   
3         13.3                                 561.98450   
4          5.0                                 390.56840   
..         ...                                       ...   
409       13.7                                4082.01500   
410        5.6                                  90.45606   
411       18.8                                 390.96960   
412        8.1                                 104.81010   
413        6.5                                  90.45606   

     Number of convenience stores  latitude  longitude  Number of bedrooms  \
0                              10  24.98298  121.54024                   1   
1                               9  24.98034  121.53951                   2   
2                               5  24.98746  121.54391                   3   
3                               5  24.98746  121.54391                   2   
4                               5  24.97937  121.54245                   1   
..                            ...       ...        ...                 ...   
409                             0  24.94155  121.50381                   3   
410                             9  24.97433  121.54310                   2   
411                             7  24.97923  121.53986                   1   
412                             5  24.96674  121.54067                   1   
413                             9  24.97433  121.54310                   2   

     House size (sqft)  
0                  575  
1                 1240  
2                 1060  
3                  875  
4                  491  
..                 ...  
409                803  
410               1278  
411                503  
412                597  
413               1097  

[414 rows x 7 columns]

In [13]:
Y = df.Price
Y

0      37.9
1      42.2
2      47.3
3      54.8
4      43.1
       ... 
409    15.4
410    50.0
411    40.6
412    52.5
413    63.9
Name: Price, Length: 414, dtype: float64

In [14]:
reg = linear_model.LinearRegression()
reg.fit(X,Y)

LinearRegression()

In [15]:
reg.coef_

array([-2.66956813e-01, -4.28835847e-03,  1.15734905e+00,  2.36489938e+02,
       -8.60667521e+00, -1.66310247e-01,  1.01996466e-03])

In [16]:
reg.intercept_

-4816.927320647164

In [17]:
reg.predict([[14.3,561.98450,7,24.98746,121.54391,5,1060]])

C:\Users\rahul\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([48.3901725])

In [18]:
reg.predict([[6.5,90.45606,9,24.97433,121.54310,2,1097]])

C:\Users\rahul\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([52.24774467])